Optionally return structured array buffer for cursor.getmulti()
jnwatson/py-lmdb pull request #264
Opened 2020-10-11 20:05 UTC by willsthompson

This adds an optimized codepath for marshaling getmulti() results into a NumPy array. In CPython it builds the structured array in a buffer and returns a memoryview. This is how to use it:

````
key_bytes, val_bytes = 4, 8
dtype = np.dtype([(f'S{key_bytes}', f'S{val_bytes}}')])
arr = np.frombuffer(
    cur.getmulti(keys, dupdata=True, dupfixed_bytes=val_bytes, key_bytes=key_bytes)
)
````

With this option, I think the argument names should change. Something like `key_bytes`/`val_bytes`, `key_size`/`val_size`, `dupfixed_key_bytes`/`dupfixed_val_bytes`, etc

2020-10-11 21:37 UTC, jnwatson requested changes

2020-10-11 21:37 UTC, jnwatson commented on tests/testlib.py
> +# ITEMS2_MULTI = [
please delete

2020-10-11 21:37 UTC, jnwatson commented on lmdb/cpython.c
> +        buffer = malloc(buffer_size * item_size);
You must make sure that buffer is freed if there's an early exit.

2020-10-11 21:40 UTC, jnwatson commented
I agree on the parameter name change. I'm pretty sure that key_bytes doesn't have to contain a size; it could just be a boolean. The size is available from keys itself.

2020-10-12 01:11 UTC, willsthompson commented
I think I got all these resolved. Now the arg names are `dupfixed_bytes` and `keyfixed`. If the latter is true, it uses the size of the first key encountered by the iterator as the fixed key size for the buffer. They still could probably use better names. Thoughts?

2020-10-12 14:11 UTC, jnwatson approved these changes

2020-10-12 14:11 UTC, jnwatson commented
Excellent.

2020-10-12 14:12 UTC, merged